### ISSUE TITLE
[FEAT] B_BUDGET - 예산설정 기능 구현

### ISSUE THREAD

**Issue by TirTir** [TirTir/Budget-Management#5]
## 📖 Describe
> 카테고리 목록(API)
> 예산 설정(API)
> 예산 설계(API)

## ✅ TODO
- [x] 카테고리 조회 서비스 작성
- [x] 예산 설정 서비스 작성
- [x] 예산 추천 서비스 작성

## 참고
> 카테고리:  `식비` `교통`
